### PR TITLE
remove functionality to translate old CEPH_SRC/FSTESTS_DIR syntax

### PR DESCRIPTION
**Pull request by ddiss**

### CODE REVIEW

**Comment by luis-henrix** [comment]
Looks good to me, let's ship it!

**Comment by luis-henrix** [comment]
hmm... I thought that button would do the merge...

**Comment by luis-henrix** [comment]
Ok, that was the right button this time.  Unfortunately the merge commit author gets a wrong email address.  Better do it without any fancy web interface next time.

**Comment by ddiss** [comment]
No worries, feel free to merge and push manually if you'd prefer - I've disabled force pushing on the master branch so there's not a lot that can go wrong by mistake.

**Pull request merged**
