### PR TITLE
Add shared folder support to rapido

### PR DESCRIPTION
**Pull request by morbidrsa**
This PR adds support for an easy setup of a shared folder between the host and the guest.

### CODE REVIEW

**Comment by morbidrsa** [comment]
@ddiss ping?

**Comment by ddiss** [comment]
> @ddiss ping?

@morbidrsa mind if I push with a VIRTFS_FOLDER -> VIRTFS_SHARE_PATH  rename squashed in?
https://github.com/ddiss/rapido/commit/497d8e68ce75b1f8baa48c0271b324095c67287a

**Comment by ddiss** [comment]
> @morbidrsa mind if I push with a VIRTFS_FOLDER -> VIRTFS_SHARE_PATH rename squashed in?
> [ddiss@497d8e6](https://github.com/ddiss/rapido/commit/497d8e68ce75b1f8baa48c0271b324095c67287a)

Bleh, a bogus rapido.conf.example entry is in that commit, make it:
https://github.com/ddiss/rapido/commit/c3147db24ffe8087ec53481cc09ff9c885d95257

**Comment by morbidrsa** [comment]
> > @morbidrsa mind if I push with a VIRTFS_FOLDER -> VIRTFS_SHARE_PATH rename squashed in?
> > [ddiss@497d8e6](https://github.com/ddiss/rapido/commit/497d8e68ce75b1f8baa48c0271b324095c67287a)
> 
> Bleh, a bogus rapido.conf.example entry is in that commit, make it:
> [ddiss@c3147db](https://github.com/ddiss/rapido/commit/c3147db24ffe8087ec53481cc09ff9c885d95257)

Nope looks good

**Comment by ddiss** [comment]
Pushed to master - thanks!

**Pull request closed without merging**
