### PR TITLE
Initramfs data verification

### PR DESCRIPTION
**Pull request by ddiss**

### CODE REVIEW

**Comment by ddiss** [comment]
The `gen_init_cpio` change requires the kernel patchset:
https://lore.kernel.org/linux-fsdevel/20211213232007.26851-1-ddiss@suse.de/T/#t

It can also run fine without it, but the `-c` parameter needs to be removed.

**Comment by morbidrsa** [comment]
From what I can tell, these changes look good to me.

Regarding the initramfs data verification, as it depends on a to be merged patchset, should we delay merging until the patches in question have reached Linus' tree?

**Comment by ddiss** [comment]
> From what I can tell, these changes look good to me.

Thanks for the review!

> Regarding the initramfs data verification, as it depends on a to be merged patchset, should we delay merging until the patches in question have reached Linus' tree?

Only the `gen_init_cpio` runner relies on not-yet-merged changes (cpio checksums with `-c`). I think what I'll do for now is just drop the `-c` parameter and add it back once the changes reach Linus' tree.

**Comment by ddiss** [comment]
> > Regarding the initramfs data verification, as it depends on a to be merged patchset, should we delay merging until the patches in question have reached Linus' tree?
> 
> Only the `gen_init_cpio` runner relies on not-yet-merged changes (cpio checksums with `-c`). I think what I'll do for now is just drop the `-c` parameter and add it back once the changes reach Linus' tree.

Pushed with this minor change squashed in:
```
--- a/cut/initramfs_gen_init_cpio.sh
+++ b/cut/initramfs_gen_init_cpio.sh
@@ -36,9 +36,9 @@ slink vdata-slink /vdata 0700 0 0
 EOF

 export tmp_vdata
-# gen_init_cpio -c option requires the kernel patchset
+# TODO: gen_init_cpio -c option requires the kernel patchset
 # initramfs: "crc" cpio format and INITRAMFS_PRESERVE_MTIME
-"${KERNEL_SRC}/usr/gen_init_cpio" -c "${tmp_vdata}/fiod.gen_init_cpio.manifest" \
+"${KERNEL_SRC}/usr/gen_init_cpio" "${tmp_vdata}/fiod.gen_init_cpio.manifest" \
        >> "$DRACUT_OUT" \
        || _fail "gen_init_cpio failed"
```

**Pull request closed without merging**
