### PR TITLE
openiscsi: add cut and autorun

### PR DESCRIPTION
**Pull request by ddiss**
Generate an image with iscsid and iscsiadm from OPENISCSI_SRC. On boot,
connect to the target at INITIATOR_DISCOVERY_ADDR, issue a SendTargets
request and then login to any discovered targets.

Signed-off-by: David Disseldorp <ddiss@suse.de>

### CODE REVIEW

**Comment by ddiss** [comment]
@gonzoleeman : Might be of interest.

**Comment by gonzoleeman** [comment]
Yes, very interesting.

**Comment by ddiss** [comment]
@gonzoleeman can I take that as a review or ack? :-)
If so, I'll merge it now as-is.

**Comment by gonzoleeman** [comment]
David: the code *looks* correct to me (the iscsi parts that I grok), and I _assume_ you've tested it (since I know you, so I know you normally would). Given that, sure, call that an Ack.

**Pull request merged**
