### PR TITLE
Simple example scripts and readme improvements

### PR DESCRIPTION
**Pull request by ddiss**

### CODE REVIEW

**Comment by ddiss** [comment]
FWIW, a rendering of the asciidoc documentation can be found at:
https://github.com/ddiss/rapido/blob/simple_example/readme.adoc

**Comment by ddiss** [comment]
I've pushed a couple of extra documentation changes which update vstart_kernel_test.txt and move it under a new doc subdir: https://github.com/ddiss/rapido/blob/simple_example/doc/ceph_vstart_kernel_client_guide.adoc

**Comment by luis-henrix** [comment]
(sorry for the delay reviewing)
This looks good to me -- the updated documentation is always welcome, and I guess the template cut/autorun scripts are a very good idea.  Thanks @ddiss

**Comment by luis-henrix** [comment]
Why do I always do this?  grrr

**Pull request merged**
